# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/call-canlii',
                'doc_host': 'https://simon-lawyer.github.io',
                'git_url': 'https://github.com/simon-lawyer/call-canlii',
                'lib_path': 'call_canlii'},
  'syms': {'call_canlii.core': {'call_canlii.core.foo': ('core.html#foo', 'call_canlii/core.py')}}}