project:
  type: website

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  google-analytics: "G-L7BN9K37E9"
  repo-actions: [issue]
  navbar:
    background: secondary
    search: true
    right:
        - text: 'About me'
          href: 'http://www.simonwallace.ca'
        - icon: github
          href: https://github.com/simon-lawyer/call-canlii

  sidebar:
    style: floating
  body-footer: 'Simon Wallace, PhD student (Osgoode Hall Law School), 2022'

metadata-files: [nbdev.yml, sidebar.yml]