# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/call-canlii',
                'doc_host': 'https://simon-lawyer.github.io',
                'git_url': 'https://github.com/simon-lawyer/call-canlii',
                'lib_path': 'callcanlii'},
  'syms': { 'callcanlii.caller': { 'callcanlii.caller.Caller': ('caller.html#caller', 'callcanlii/caller.py'),
                                   'callcanlii.caller.Caller.__init__': ('caller.html#caller.__init__', 'callcanlii/caller.py'),
                                   'callcanlii.caller.Caller.case_cites_of_cases': ( 'caller.html#caller.case_cites_of_cases',
                                                                                     'callcanlii/caller.py'),
                                   'callcanlii.caller.Caller.case_cites_of_legislation': ( 'caller.html#caller.case_cites_of_legislation',
                                                                                           'callcanlii/caller.py'),
                                   'callcanlii.caller.Caller.case_metadata': ('caller.html#caller.case_metadata', 'callcanlii/caller.py'),
                                   'callcanlii.caller.Caller.cites_of_case': ('caller.html#caller.cites_of_case', 'callcanlii/caller.py'),
                                   'callcanlii.caller.Caller.isolate_id': ('caller.html#caller.isolate_id', 'callcanlii/caller.py'),
                                   'callcanlii.caller.Caller.list_decisions': ('caller.html#caller.list_decisions', 'callcanlii/caller.py'),
                                   'callcanlii.caller.Caller.list_tribunals': ( 'caller.html#caller.list_tribunals',
                                                                                'callcanlii/caller.py')}}}